name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - packaging=20.0
  - python=3.9
  - pyyaml=5.3.1
  - click=8.1
  - cloudpickle=1.5.0
  - partd=1.4.0
  - fsspec=2021.09.0
  - importlib-metadata=4.13.0
  - toolz=0.10.0
  # optional dependencies pulled in by pip install dask[array,dataframe]
  - numpy=1.21
  - pandas=2.0
  # optional dependencies pulled in by pip install dask[diagnostics]
  - bokeh=2.4.2
  - jinja2=2.10.3
  # optional dependencies pulled in by pip install dask[complete]
  - pyarrow=7.0
  - lz4=4.3.2
  # optional dependencies used by dask
  - cachey=0.1.1
  - crick=0.0.3
  - cytoolz=0.11.0
  - dask-ml=1.4.0
  - fastavro=1.1.0
  - fastparquet=0.8.2
  - h5py=2.10.0
  - ipycytoscape=1.0.1
  - IPython=7.16.1
  - matplotlib=3.4.1
  - mimesis=5.3.0
  - mmh3=2.5.1
  - psutil=5.7.2
  - python-cityhash=0.4.6
  - python-graphviz=0.8.4
  - python-snappy=0.5.4
  - python-xxhash=2.0.0
  - s3fs=2021.9.0
  - scikit-image=0.17.2
  - scipy=1.5.2
  - sparse=0.12.0
  - sqlalchemy=1.4.16
  - tblib=1.6.0
  - tiledb-py=0.8.1
  - zarr=2.12.0
  - pip
  - pip:
      # optional dependencies pulled in by pip install dask[distributed]
      - git+https://github.com/dask/distributed
      - git+https://github.com/dask/dask-expr
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
