# This job includes coverage
name: test-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  # required dependencies
  - python=3.11
  - packaging
  - pyyaml
  - click
  - cloudpickle
  - partd
  - fsspec
  - importlib_metadata
  - toolz
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
  - moto<5
  # Optional dependencies
  - mimesis
  - numpy
  - pandas=2
  - numba
  - flask
  - fastparquet
  - h5py
  - pytables
  - zarr
  # `tiledb-py=0.17.5` lead to strange seg faults in CI, However 0.18 is needed for 3.11
  # https://github.com/dask/dask/pull/9569
  # - tiledb-py # crashes on Python 3.11
  # - pyspark
  # - tiledb # crashes on Python 3.11
  - xarray
  - sqlalchemy
  - pyarrow>=13
  - coverage
  - jsonschema
  # other -- IO
  - boto3
  - botocore
  - bokeh
  - httpretty
  - aiohttp
  - s3fs>=2021.9.0
  # Need a new `crick` release with support for `numpy=1.24+`
  # https://github.com/dask/crick/issues/25
  # - crick
  - cytoolz
  - distributed
  - ipython
  - ipycytoscape
  # until https://github.com/jupyter-widgets/ipywidgets/issues/3731 is fixed
  - ipywidgets<8.0.5
  - ipykernel<6.22.0
  - lz4
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - python-cityhash
  - python-xxhash
  - mmh3
  - jinja2
  - pip
  - pip:
    - git+https://github.com/dask/distributed
    - git+https://github.com/dask/dask-expr
